export const SET_AI_CHAT_MESSAGES = "SET_AI_CHAT_MESSAGES";
export const ADD_AI_CHAT_MESSAGE = "ADD_AI_CHAT_MESSAGE";
export const SET_AI_CHAT_HISTORY_LOADING = "SET_AI_CHAT_HISTORY_LOADING";
export const SET_AI_CHAT_SENDING = "SET_AI_CHAT_SENDING";
