// GlobalTix Action Types
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_LOADING = "SET_LOADING";
export const SET_LOADING_MORE = "SET_LOADING_MORE";
export const SET_ERROR = "SET_ERROR";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
export const SET_PRODUCT_OPTIONS = "SET_PRODUCT_OPTIONS";
export const SET_COUNTRIES = "SET_COUNTRIES";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CITIES = "SET_CITIES";
export const SET_FILTERS = "SET_FILTERS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const SET_FAVORITES = "SET_FAVORITES";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const SET_BOOKING = "SET_BOOKING";
export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const SET_TOTAL_PRODUCTS = "SET_TOTAL_PRODUCTS";
export const SET_HAS_MORE = "SET_HAS_MORE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_GLOBALTIX_PAYMENT_DATA = "SET_GLOBALTIX_PAYMENT_DATA";

