export const SET_COUNTRIES = "SET_COUNTRIES";

export const SET_USER_LOCATION = "SET_USER_LOCATION";
export const SET_USER_LOCATION_LOADING = "SET_USER_LOCATION_LOADING";
export const SET_MARKETING_POPUP = "SET_MARKETING_POPUP";
export const SET_HAS_SHOWN_MARKETING_POPUP = "SET_HAS_SHOWN_MARKETING_POPUP";

